### ISSUE TITLE
Chinese translation is incomplete ...

### ISSUE THREAD

**Issue by pedrolcl** [pedrolcl/VMPK#14]
The first, very conspicuous, untranslated elements are the note names:
![image](https://github.com/pedrolcl/VMPK/assets/15184708/fbe9e700-7cf3-4719-975f-fe0c6e5f7017)
But also the palette names and descriptions, in the palette editor dialog:
![image](https://github.com/pedrolcl/VMPK/assets/15184708/87c077ea-ebf3-447c-925d-96366e64b855)
And the MIDI drivers configurations. Here is the FluidSynth configuration dialog:
![image](https://github.com/pedrolcl/VMPK/assets/15184708/0cc74949-abb1-4b70-8051-4f01e8d5f0fc)
But there are also configuration dialogs for the Sonivox and Network drivers:

![image](https://github.com/pedrolcl/VMPK/assets/15184708/b5343a57-b576-4114-a400-2ad8300ba244)

All the above elements shown in VMPK come from the Drumstick::Widgets library, which has its own translations. This is similar to the OK and Cancel buttons, which belong to the Qt Widgets library translations.

Here are the Drumstick::Widgets [translation files](https://github.com/pedrolcl/drumstick/tree/master/library/widgets/translations).

Wiki about [translations documentation](https://github.com/pedrolcl/VMPK/wiki/Translations).

<hr/>

There are a few other words that cannot be translated (yet) not only for Chinese, but for any other language as well. In the tool bars you may find...

* Bank names
* Instrument (patch) names
* Controller names
* Extra controller names

![image](https://github.com/pedrolcl/VMPK/assets/15184708/8b88654b-1d56-4268-a4a7-c245fb01fb10)

This is a known pending issue, [reported at SF](https://sourceforge.net/p/vmpk/bugs/76/)

**Comment by pedrolcl** [comment]
@hycinth22 : You may be interested in this report

**Comment by hycinth22** [comment]
The note names do not need to be translated and untranslatable. Chinese musicians directly call these English names of notes.

I'll take a look at the other elements

**Comment by hycinth22** [comment]
For the palette editor dialog and the MIDI drivers configurations, I have translated them and they are in Chinese in my build. I don't know why it didn't work in the latest release version and need to find out why.

For elements from the Drumstick::Widgets library, yeah, it does need more work.

**Comment by pedrolcl** [comment]
Thanks @hycinth22 for all your contributions! [drumstick v2.8.1](https://sourceforge.net/projects/drumstick/files/2.8.1/) has been released today, including your updated translations, and VMPK 0.8.10 will be released this weekend.
