### ISSUE TITLE
Sending the MIDI reset doesn't reset all controllers in the UI 

### ISSUE THREAD

**Issue by pedrolcl** [pedrolcl/VMPK#21]
[SF ticket 90](https://sourceforge.net/p/vmpk/bugs/90)

Manually added extra controllers aren't reset when pressing the Reset button.

The Volume controller doesn't reset on first button click but on the second. When the keep consistency option is set it seems to reset at the first click.

The selected instrument isn't reset either.

Created by @berarma

**Comment by pedrolcl** [comment]
The [MIDI 1.0 Specifications](https://midi.org/specifications/midi1-specifications/) defines the "Reset All Controllers" MIDI message:

> When a device receives the Reset All Controllers message (121), it should reset the condition of all its
controllers (continuous and switch controllers, pitch bend, and pressures) to what it considers an ideal
initial state (Mod wheel to 0, Pitch Bend to center, etc.). Reception follows the same rules as All Notes
Off — Ignore if Omni is On .
Sequencers that wish to implement Reset All Controllers, but want to accommodate devices that do not
implement this command, should send what they believe to be the initial state of all controllers first,
followed by this message. Devices that respond to this message will end up in their preferred state,
while those that do not will still be in the sequencer's chosen initialized state.

The above definition is not detailed, but there is another document, [Recommended Practice (RP-015)](https://midi.org/specifications/midi1-specifications/midi-1-addenda/response-to-reset-all-controllers) providing more information:

* Set Expression (11) to 127
* Set Modulation (1) to 0
* Set Pedals (64, 65, 66, 67) to 0
* Set Registered and Non-registered parameter number LSB and MSB (98-101) to null value (127)
* Set pitch bender to center (64/0)
* Reset channel pressure to 0
* Reset polyphonic pressure for all notes to 0.
* Do NOT reset Bank Select (0/32)
* Do NOT reset Volume (7)
* Do NOT reset Pan (10)
* Do NOT reset Program Change
* Do NOT reset Effect Controllers (91-95)
* Do NOT reset Sound Controllers (70-79)
* Do NOT reset other channel mode messages (120-127)
* Do NOT reset registered or non-registered parameters.

**Comment by berarma** [comment]
I wasn't aware of the best practices when creating this ticket. The extra controllers I was testing shouldn't be reset so it's working well there. Other controllers seem to reset correctly.

Except the volume and also pan which are being reset when they shouldn't, in theory. We can't know if the commanded device is following best practices.

Thanks for looking into it.

**Comment by pedrolcl** [comment]
Another source (the MIDI Brainwashing center) [says](http://midi.teragonaudio.com/tech/midispec/ctloff.htm):

* [Volume](http://midi.teragonaudio.com/tech/midispec/vol.htm) should be set to 100.
* [Pan](http://midi.teragonaudio.com/tech/midispec/pan.htm) should be set to center (i.e., 64 for both coarse, as well as fine if used).

That source was the only freely available MIDI specifications before the MIDI Association was opened.

Roland didn't follow the recommended practice in some products, like the [JV-80](http://cdn.roland.com/assets/media/pdf/JV-80_OM.pdf):

![image](https://github.com/pedrolcl/VMPK/assets/15184708/c58f9088-a807-400b-a708-40e6e510aeaa)

**Comment by berarma** [comment]
That was the information I was handling at first. For newer devices/softsynths I would follow the newest document.

Anyway, the weirdest thing is that the controls are reset only the second time the button is pressed. I've also noticed that toggling the keep consistency option without restarting the application changes the outcome.

**Comment by pedrolcl** [comment]
> Anyway, the weirdest thing is that the controls are reset only the second time the button is pressed.

This has been fixed in commit 0d7698e
