### ISSUE TITLE
Fluidsynth backend does not load DLS files

### ISSUE THREAD

**Issue by spessasus** [pedrolcl/VMPK#31]
![image](https://github.com/user-attachments/assets/d4d6c608-e1a2-4e12-bb59-61ca54d1b3cc)

## Problem
As the title mentioned, fluidsynth built into the VMPK fails to load a DLS file (gm.dls from drivers in this example)
**Standalone fluidsynth build (command line) loads the file fine.**

VMPK should be able to use DLS via fluidsynth like the standalone version.

## Version
latest from sourceforge:
![image](https://github.com/user-attachments/assets/90bc758b-f6f8-4ca4-aa84-6b6e455f4a5e)

Windows 10 64-bit

**Comment by pedrolcl** [comment]
Yes, this version of VMPK was compiled with the libraries provided by [vcpkg](https://vcpkg.io/) which includes [fluidsynth](https://vcpkg.io/en/package/fluidsynth) and most dependencies, but not [libinstpatch](https://vcpkg.io/en/packages?query=libinstpatch) that is required for DLS support.

I might switch to [msys2](https://www.msys2.org/) in the future, which also includes [fluidsynth](https://packages.msys2.org/search?q=fluidsynth) without [libinstpatch](https://packages.msys2.org/search?q=libinstpatch) so this won't change the situation.

**Comment by spessasus** [comment]
What's the point of reporting a bug when all I get is "fix it yourself"? Not very cool IMO.

**Comment by pedrolcl** [comment]
> What's the point of reporting a bug when all I get is "fix it yourself"? Not very cool IMO.

This is not a bug. It could be an enhancement request (see the labels).

And I am not selling a product. I am a volunteer that is expending free time in this and also other open source projects. It is not cool when users pretend to have the right to demand that I do more work for free in order to satisfy their wishes.
