### ISSUE TITLE
Text compressed on the GUI labels of v0.8.9

### ISSUE THREAD

**Issue by hellishvictor** [pedrolcl/VMPK#5]
Hi, I've noticed that the text on the new v0.8.9 looks like "compressed"; for example, just check how the "r" seems to be almost inside the "T" on "Transposición":
v0.8.8
![sshot-1](https://github.com/pedrolcl/VMPK/assets/34694956/ff370213-45cf-43de-91be-4f787b6e4caf)
v0.8.9
![sshot-2](https://github.com/pedrolcl/VMPK/assets/34694956/dbf54e98-de87-4b0c-86f7-c005e4949b93)
Cheers.

**Comment by pedrolcl** [comment]
Without some context, the screenshots do not say anything. I need to know, as a minimum, the operating system/version where your screenshots have been taken. Also, the origin (packaging) of your programs.You may for instance take screenshots of the "Acerca de" dialog.

**Comment by hellishvictor** [comment]
There is other place than sourceforge for download the program? I didn't know, I've always download it from [there](https://sourceforge.net/projects/vmpk/files/vmpk/). Anyway, I'm on Win 7 x64 SP1 and here are the screenshots, where can be noticed how in "Inflexión" looks like "In flexión" in the latest version:
v0.8.9
![sshot-2](https://github.com/pedrolcl/VMPK/assets/34694956/5658e9fb-c42e-4602-b759-c6c09dc60227)
![sshot-1](https://github.com/pedrolcl/VMPK/assets/34694956/a224306d-412f-4249-9f52-fd6045934610)

v0.8.8
![sshot-3](https://github.com/pedrolcl/VMPK/assets/34694956/0e7e1b1f-e186-4625-8e19-f7deea122425)
![sshot-4](https://github.com/pedrolcl/VMPK/assets/34694956/78a7d189-a9a1-4f58-8ebc-d21ee0aeb325)

**Comment by pedrolcl** [comment]
> There is other place than sourceforge for download the program? I didn't know, I've always download it from [there](https://sourceforge.net/projects/vmpk/files/vmpk/).

VMPK works on several operating systems. You didn't specify your OS in the first comment. On Linux, you may find the program on repositories of many Linux distributors and you may download an AppImage from Sourceforge, but there is also a Flatpak version that you may get on FlatHub. And for Windows, you may also get a [WinGet](https://learn.microsoft.com/es-es/windows/package-manager/winget/) package in addition of the Sourceforge installers.

**Comment by pedrolcl** [comment]
About your report: I am not able to test VMPK on Windows 7 anymore. My advice is that if you don't update Windows, then don't update your applications either.

Anyway, font rendering in VMPK is totally depending on Qt (5.15.10 in this case). You may try some available Qt options, and see if it makes a difference for you. See this documentation:

* https://doc.qt.io/qt-5/qguiapplication.html
* https://doc.qt.io/qt-5/qt-conf.html

qt.conf:

```
[Platforms]
WindowsArguments = fontengine=freetype
```

Try also fontengine=default or directwrite, and search also for Qt bugs, like:  [QTBUG-83161](https://bugreports.qt.io/browse/QTBUG-83161)

**Comment by hellishvictor** [comment]
Thank you for your advise but I won't miss this update since it removes the splash screen; it looks decent switching the language to english.
