### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by hellishvictor** [pedrolcl/VMPK#6]
Hi, VMPK store its setting on the Windows registry and I wonder if there's a way to store them in a .cfg file instead, and this way, use it as a portable program on a USB and leave no traces. Definelly that would be an awesome feature.
Cheers.

**Comment by pedrolcl** [comment]
![imagen](https://github.com/pedrolcl/VMPK/assets/15184708/45153ab2-1d31-489b-8545-a8b0098e8ea1)

**Comment by pedrolcl** [comment]
You may also see the Unix man page, that is available on several Internet places:

https://www.mankier.com/1/vmpk

![image](https://github.com/pedrolcl/VMPK/assets/15184708/9bc6f798-cc5b-4da5-ba97-c27d055b9260)

**Comment by hellishvictor** [comment]
That's really awesome; now I'll create a batch file for select the .conf files so the program can be for launch with different settings.
Thank you!
